Task3
TheGreatAjax/Clinic pull request #5
Opened 2022-10-19 06:59 UTC by TheGreatAjax

2022-10-23 07:51 UTC, Vixorem requested changes

2022-10-23 07:51 UTC, Vixorem commented on clinic/Entities/Appointment.cs
> +        public DateOnly Day { get; set; }
Можно это убрать и заюзать datetime в полях ниже. Как раз будет и дата и время

2022-10-23 07:51 UTC, Vixorem commented on clinic/Services/AppointmentService.cs
> +    public Result<Appointment> BookAppointment(User patient, Doctor? doc, DateOnly day, TimeOnly time)
Классно, хорошо прочекал кейсы

2022-10-23 07:51 UTC, Vixorem commented on clinic/Services/AppointmentService.cs
> +    public Result<List<DateOnly>> GetFreeDates(Specialization spec)
Лучше datetime. В течение дня в разное время могут быть

2022-10-24 02:39 UTC, foggy21 approved these changes

2022-10-24 02:39 UTC, foggy21 commented on clinic/Entities/Doctor.cs
> +            Specialization = spec;
Соррян за духоту, но spec точно хорошее сокращение для переменной? Я бы написал такое же наименование только с маленькой буквы.

2022-10-24 02:39 UTC, foggy21 commented on clinic/Services/ScheduleService.cs
> +        if (finish < start)
А если finish == start?

2022-10-25 11:42 UTC, Vixorem approved these changes

2022-10-26 08:13 UTC, merged